const questions = [
    {
        question: "That's what I do, I drink and I know things. (GOT) " ,
        choice1: 'Tryion Lannister',
        choice2: 'Jon Snow',
        choice3: 'Bran Stark',
        choice4: 'Theon Greyjoy', 
        answer: 1,
    },
    {
        question: 'You know what I like about people? They stack so well. (House of Cards)',
        choice1: 'Doug Stamper',
        choice2: 'Tom Hammerschmidt',
        choice3: 'Franck Underwood',
        choice4: 'Seth Grayson', 
        answer: 3,
    },
    {
        question: "I'm not in the meth business. I'm in the empire business. (Breaking Bad)" ,
        choice1: 'Jesse Pinkman',
        choice2: 'Walter White',
        choice3: 'Hank Schrader',
        choice4: 'Walter White Jr.', 
        answer: 2,
    },
    {
        question: 'Shut up Anderson! You lower the IQ of the whole street. (Sherlock)',
        choice1: 'Mycroft Holmes',
        choice2: 'Inspector Lestrade',
        choice3: 'John H. Watson',
        choice4: 'Sherlock Holmes', 
        answer: 4,
    },
    {
        question: 'We were on a break. (Friends)',
        choice1: 'Chandler Bing',
        choice2: 'Ross Geller',
        choice3: 'Monica Geller',
        choice4: 'Rachel Green', 
        answer: 2,
    },
    {
        question: 'Kabhi kabhi lagta hai ki apun hi bhagwan hai. (Sacred Games)',
        choice1: 'Ganesh Gaitonde',
        choice2: 'Sartaj Singh',
        choice3: 'Guru ji',
        choice4: 'Parulkar', 
        answer: 1,
    },
    {
        question: 'If you think this has a happy ending you haven’t been paying attention. (GOT)',
        choice1: 'Jaime Lannister',
        choice2: 'Jon Snow',
        choice3: 'Ramsay Bolton',
        choice4: 'Sandor Clegane', 
        answer: 3,
    },
    {
        question: 'When you play the game of thrones, you win or you die. (GOT)',
        choice1: 'Missandei',
        choice2: 'Sansa Stark',
        choice3: 'Arya Stark',
        choice4: 'Cersei Lannister', 
        answer: 4,
    },
    {
        question: 'It doesn’t matter what we want. Once we get it, then we want something else. (GOT)',
        choice1: 'Samwell Tarly',
        choice2: 'Lord Baelish',
        choice3: 'Lord Varys',
        choice4: 'Jaime Lannister', 
        answer: 2,
    },
    {
        question: 'Andar maamla thoda tamtamaya hua hai, soch-samajh ke muh kholiyega. Ek kaam kariye, aap muh kholiye hi mat (Panchayat)',
        choice1: 'Brij Bhushan Dubey',
        choice2: 'Abhishek Tripathi',
        choice3: 'Vikas',
        choice4: 'Prahlad Pandey', 
        answer: 1,
    },
    {
        question: 'Tod toh taala rahe the, darwaza se mazboot toh taala nikla. (Panchayat)',
        choice1: 'Brij Bhushan Dubey',
        choice2: 'Abhishek Tripathi',
        choice3: 'Vikas',
        choice4: 'Prahlad Pandey', 
        answer: 3,
    },
    {
        question: 'Bacche 2 saal mein KOTA se nikal jaate hain! KOTA saalon tak bacchon se nahi nikalta. (Kota Factory)',
        choice1: 'Balmukund Meena',
        choice2: 'Jeetu Bhaiya',
        choice3: 'Vaibhav Pandey',
        choice4: 'Maheshwari Sir', 
        answer: 2,
    },
    {
        question: '7 saal, 4 saal graduation ke,aur 3 saal job ke lagte hai,iss sadme se nikalne ke liye. Aur Fraud Baazi ki saaja pta kitni hai India mei? 7 Saal! (Kota Factory)',
        choice1: 'Maheshwari Sir',
        choice2: 'Uday Gupta',
        choice3: 'Vaibhav Pandey',
        choice4: 'Jeetu Bhaiya', 
        answer: 4,
    },
    {
        question: 'Abe rank unki improve hoti hai jinki aa rahi hoti hai aur tumhari to chudail (Witch) kha jayegi! (Kota Factory)',
        choice1: 'Balmukund Meena',
        choice2: 'Jeetu Bhaiya',
        choice3: 'Vaibhav Pandey',
        choice4: 'Maheshwari Sir', 
        answer: 2,
    },
    {
        question: 'Jab desh ke PM ka imaan nahin toh apun sidhe raaste chal ke kya karega. (Sacred Games)',
        choice1: 'Guru ji',
        choice2: 'Sartaj Singh',
        choice3: 'Ganesh Gaitonde',
        choice4: 'Parulkar', 
        answer: 3,
    },
    {
        question: 'Dear God, what is it like in your funny little brains? It must be so boring! (Sherlock)',
        choice1: 'Mycroft Holmes',
        choice2: 'Professor Moriarty',
        choice3: 'Sherlock Holmes',
        choice4: 'Inspector Lestrade', 
        answer: 3,
    },
    {
        question: 'In a world of locked rooms the man with the key is king. And honey, you should see me in a crown. (Sherlock)',
        choice1: 'Sherlock Holmes',
        choice2: 'Mycroft Holmes',
        choice3: 'Molly Hooper',
        choice4: 'Jim Moriarty', 
        answer: 4,
    },
    {
        question: "Don't make people into heroes, John. Heroes don't exist and if they did I wouldn't be one of them. (Sherlock)",
        choice1: 'John H. Watson',
        choice2: 'Sherlock Holmes',
        choice3: 'Mycroft Holmes',
        choice4: 'Jim Moriarty', 
        answer: 2,
    },
    {
        question: 'I’m not a psychopath, Anderson. I’m a high-functioning sociopath. Do your research. (Sherlock)',
        choice1: 'John H. Watson',
        choice2: 'Sherlock Holmes',
        choice3: 'Mycroft Holmes',
        choice4: 'Jim Moriarty', 
        answer: 2,
    },
    {
        question: 'Let the matriarchy begin. (Money Heist)',
        choice1: 'Tokyo',
        choice2: 'Nairobi',
        choice3: 'Raquel Murillo',
        choice4: 'Monica Gaztambide', 
        answer: 2,
    },
    {
        question: 'The most important moments are the ones that make you realize there’s no turning back. You’ve crossed a line, and you’re stuck on the other side now. (Money Heist)',
        choice1: 'Professor',
        choice2: 'Denver',
        choice3: 'Berlin',
        choice4: 'Tokyo', 
        answer: 4,
    },
    {
        question: "First times are so special. Unique. But the last times are beyond comparison. They are priceless. But people don't normally know it's their last time. (Money Heist)",
        choice1: 'Berlin',
        choice2: 'Denver',
        choice3: 'The Professor',
        choice4: 'Tokyo', 
        answer: 3,
    },
    {
        question: "Risk hai toh isq hai. (Scam 1992)",
        choice1: 'Manu Mundra',
        choice2: 'K. Madhavan',
        choice3: 'Bhushan Bhatt',
        choice4: 'Harshad Mehta', 
        answer: 4,
    },
    {
        question: "Profit dikhta hai toh har koi jhukta hai. (Scam 1992)",
        choice1: 'Harshad Mehta',
        choice2: 'Sucheta Dalal',
        choice3: 'S. Venkitaramanan',
        choice4: 'Tyagi', 
        answer: 1,
    },
    {
        question: "Attack me bhi gun, defense me bhi gun. Hum banayenge Mirzapur ko Amirica. (Mirzapur)",
        choice1: 'Bablu Pandit',
        choice2: 'Akhandanand Tripathi',
        choice3: 'Munna Tripathi',
        choice4: 'Guddu Pandit', 
        answer: 4,
    },
    {
        question: "Neta banna hai toh gundey paalo. Gundey mat bano. (Mirzapur)",
        choice1: ' Satyanand Tripathi',
        choice2: 'Kaleen Bhaiya',
        choice3: 'Bablu Pandit',
        choice4: 'Sharad Shukla', 
        answer: 2,
    },
    {
        question: "Darr ki yahi dikkat hain, ki kabhi bhi Khatam ho sakta hai. (Mirzapur)",
        choice1: 'Satyanand Tripathi',
        choice2: 'Kaleen Bhaiya',
        choice3: 'Guddu Pandit',
        choice4: 'Sharad Shukla', 
        answer: 2,
    },
    {
        question: "Guns ki maddad se darr nahi badhana hai, darr ki maddad se guns badhani hai. (Mirzapur)",
        choice1: 'Bablu Pandit',
        choice2: 'Munna Tripathi',
        choice3: 'Kaleen Bhaiya',
        choice4: 'Sharad Shukla', 
        answer: 1,
    },
    {
        question: "Suru majburi mein kiye the…..Ab maza aa rahe hain. (Mirzapur)",
        choice1: 'Guddu Pandit',
        choice2: 'Munna Tripathi',
        choice3: 'JP Yadav',
        choice4: 'Sharad Shukla', 
        answer: 1,
    },
    {
        question: "Jaake Dekh Record me ke Kaun hai, Insaan hai ke Bhagwan! (Sacred Games)",
        choice1: 'Inspector Sartaj Singh',
        choice2: 'Guru ji',
        choice3: 'Bunty',
        choice4: 'Ganesh Gaitonde', 
        answer: 4,
    },
    {
        question: "Murga chahiye mereko. (Sacred Games)",
        choice1: 'Inspector Sartaj Singh',
        choice2: 'Ganesh Gaitonde',
        choice3: 'Bunty',
        choice4: 'Parulkar', 
        answer: 2,
    },
    {
        question: "Bagwaan ko maante ho kya? (Sacred Games)",
        choice1: 'Ganesh Gaitonde',
        choice2: 'Kukoo',
        choice3: 'Bunty',
        choice4: 'Parulkar', 
        answer: 1,
    },
     {
        question: "You're going to die tomorrow, Lord Bolton. Sleep well. (GOT)" ,
        choice1: 'Daenerys Targaryen',
        choice2: 'Cersei Lannister',
        choice3: 'Sansa Stark',
        choice4: 'Arya Stark', 
        answer: 3,
    },
    {
        question: "Hindi philam ke hero hain hum, humein koi nahi maar sakta, hum amar hain… (Mirzapur)",
        choice1: 'Akhandanand Tripathi',
        choice2: 'Munna Tripathi',
        choice3: 'Guddu Pandit',
        choice4: 'Maqbool', 
        answer: 2,
    },
    {
        question: "Jo aaya hai, wo jayega bhi bas marzi humari hogi. (Mirzapur)",
        choice1: 'Kaleen Bhaiya',
        choice2: 'Maqbool',
        choice3: 'Guddu Pandit',
        choice4: 'Munna Tripathi', 
        answer: 1,
    },
    {
        question: "Bauji pagla gaye hain, unka dimagh unke ghutno mein hai aur unke ghutne to kaam karte hai nahi. (Mirzapur)",
        choice1: 'Kaleen Bhaiya',
        choice2: 'Bablu Pandit',
        choice3: 'Guddu Pandit',
        choice4: 'Munna Tripathi', 
        answer: 4,
    },
    {
        question: "Bablu aur Sweety ka udhaar hai humpe, chukana hai (Mirzapur)",
        choice1: 'Dimpy',
        choice2: 'Munna Tripathi',
        choice3: 'Guddu Pandit',
        choice4: 'Golu Gupta', 
        answer: 3,
    },
    {
        question: "Aur hum ek naya niyam add kar rahe hain, Mirzapur ki gaddi pe baithne wala kabhi bhi niyam badal sakta hai (Mirzapur)",
        choice1: 'Kaleen Bhaiya',
        choice2: 'Munna Tripathi',
        choice3: 'Guddu Pandit',
        choice4: 'Golu Gupta', 
        answer: 2,
    },
    {
        question: "Jeet ki guarantee tabhi hai jab jeet aur haar dono tumhare control mein ho. (Mirzapur)",
        choice1: 'Kaleen Bhaiya',
        choice2: 'Beena Tripathi',
        choice3: 'Golu Gupta',
        choice4: 'Satyanand Tripathi', 
        answer: 4,
    },
    {
        question: "Well, maybe I don’t need your money. Wait, wait, I said maybe! (Friends)",
        choice1: 'Joey Tribbiani',
        choice2: 'Monica Geller',
        choice3: 'Rachel Green',
        choice4: 'Jack Geller', 
        answer: 3,
    },
    {
        question: "How you doin'? (Friends)",
        choice1: 'Joey',
        choice2: 'Jack Geller',
        choice3: 'Chandler Bing',
        choice4: 'Phoebe Buffay', 
        answer: 1,
    },
    {
        question: "Joey doesn’t share food! (Friends)",
        choice1: 'Rachel Green',
        choice2: 'Joey Tribbiani',
        choice3: 'Chandler Bing',
        choice4: 'Jack Geller', 
        answer: 2,
    },
    {
        question: "What’s not to like? Custard: good. Jam: good. Meat: good! (Friends)",
        choice1: 'Rachel Green',
        choice2: 'Joey Tribbiani',
        choice3: 'Monica Geller',
        choice4: 'Phoebe Buffay', 
        answer: 2,
    },
    {
        question: "They don’t know that we know they know we know. (Friends)",
        choice1: 'Chandler Bing',
        choice2: 'Joey Tribbiani',
        choice3: 'Monica Geller',
        choice4: 'Phoebe Buffay', 
        answer: 4,
    },
    {
        question: "You can’t just give up. Is that what a dinosaur would do? (Friends)",
        choice1: 'Chandler Bing',
        choice2: 'Joey Tribbiani',
        choice3: 'Rachel Green',
        choice4: 'Phoebe Buffay', 
        answer: 2,
    },
    {
        question: "It tastes like feet! (Friends)",
        choice1: 'Ross',
        choice2: 'Rachel',
        choice3: 'Joey',
        choice4: 'Chandler', 
        answer: 1,
    },
]

export default questions